"""
Curved grid sweep case — generated by curved_grid_pipeline  [2026-05-06 15:58]

Single run:  python curved_grid_pipeline.py --config curved_grid_case_example_sweep.py
Dry-run:     python curved_grid_pipeline.py --config curved_grid_case_example_sweep.py --dry-run
Sweep:       python curved_grid_pipeline.py --config curved_grid_case_example_sweep.py --sweep
Array task:  python curved_grid_pipeline.py --config curved_grid_case_example_sweep.py \
                 --sweep-task $SLURM_ARRAY_TASK_ID
"""
import math
from curved_grid_pipeline import (
    Aperture, Chamfer, BeamletPair, GridCurvature,
    CurvedGridDefinition, CurvedSimulationCase,
    make_apertures_from_pairs,
    concentric_accel_radius, concentric_accel_offsets,
)

# ── Electrode geometry ──────────────────────────────────────────
R_SCR_M         = 0.3   # screen radius of curvature (m)
R_ACC_M         = 0.292   # accel  radius of curvature (m)  [concentric]
SCREEN_T_M      = 0.006
ACCEL_T_M       = 0.006
GAP_AFTER_M     = 0.002
VS_V            = 0.0
VA_V            = -10000.0
AP_RAD_M     = 0.002

# ── Aperture offsets (m) ─────────────────────────────────────────
SCREEN_OFFSETS_M = [0]
# Arc-length on the accel sphere from the concentric (zero-steering) position.
STEERING_ARCS_M  = [0]


# ── Parameterised case factory ────────────────────────────────────
def make_case(**overrides):
    """Return a CurvedSimulationCase built from module constants.

    Each constant is replaced by the corresponding value in *overrides*
    when supplied, allowing the sweep runner to vary individual
    parameters without mutating module state.
    """
    # Accept either the short name (used in SweepAxis.name and the run-tag
    # encoding, e.g. "AP_RAD", "R_SCR") or the full "_M" name.  A plain
    # overrides.get("X_M", X_M) silently drops a SweepAxis named "X" and
    # falls back to the module default, producing sweeps that look correct
    # in the directory tag but never actually vary the parameter.
    def _ov(*keys, default):
        for k in keys:
            if k in overrides:
                return overrides[k]
        return default

    r_scr_m      = _ov("R_SCR",      "R_SCR_M",     default=R_SCR_M)
    r_acc_m_base = _ov("R_ACC",      "R_ACC_M",     default=R_ACC_M)
    screen_t_m   = _ov("SCREEN_T",   "SCREEN_T_M",  default=SCREEN_T_M)
    accel_t_m    = _ov("ACCEL_T",    "ACCEL_T_M",   default=ACCEL_T_M)
    gap_after_m  = _ov("GAP_AFTER",  "GAP_AFTER_M", default=GAP_AFTER_M)
    vs_v         = _ov("VS_V",       default=VS_V)
    va_v         = _ov("VA_V",       default=VA_V)
    ap_radius_m  = _ov("AP_RAD",     "AP_RAD_M", default=AP_RAD_M)

    # Re-derive R_ACC_M when R_SCR or geometry changes (only treat R_ACC as
    # explicitly set if either short or long form was passed).
    r_acc_explicit = ("R_ACC" in overrides) or ("R_ACC_M" in overrides)
    if not r_acc_explicit:
        r_acc_m = concentric_accel_radius(
            r_scr_m, screen_t_m, gap_after_m, SCREEN_OFFSETS_M
        )
    else:
        r_acc_m = r_acc_m_base

    pairs = [
        BeamletPair(
            screen_offset_m=s,
            steering_arc_m=arc,
            screen_radius_m=ap_radius_m,
        )
        for s, arc in zip(SCREEN_OFFSETS_M, STEERING_ARCS_M)
    ]
    screen_apertures, accel_apertures = make_apertures_from_pairs(
        pairs, mirror=False, R_scr_m=r_scr_m, R_acc_m=r_acc_m
    )

    return CurvedSimulationCase(
        grids=[
            CurvedGridDefinition(
                name="screen",
                voltage_v=vs_v,
                thickness_m=screen_t_m,
                gap_after_m=gap_after_m,
                apertures=screen_apertures,
                curvature=GridCurvature(radius_m=r_scr_m, concave_upstream=True),
                mirror=True,
            ),
            CurvedGridDefinition(
                name="accel",
                voltage_v=va_v,
                thickness_m=accel_t_m,
                gap_after_m=0.0,
                apertures=accel_apertures,
                curvature=GridCurvature(radius_m=r_acc_m, concave_upstream=True),
                mirror=True,
            ),
        ],
        env={
        "ENABLE_IONS": overrides.get("ENABLE_IONS", 1),
        "H": overrides.get("H", 0.0001),
        "PLASMA_NI_M3": overrides.get("PLASMA_NI_M3", 1e+16),
        "PNG_NAME": overrides.get("PNG_NAME", "curved_grid_geom.png"),
        "RESULTS_DIR": overrides.get("RESULTS_DIR", "results"),
        "RUN_PREFIX": overrides.get("RUN_PREFIX", "curved_grid_PerBExpansionTest_1B_300mRad_2mmAPRad_4mmGap"),
        "RUN_SOLVE": overrides.get("RUN_SOLVE", 1),
        "SC_FACTOR": overrides.get("SC_FACTOR", 0.0005),
        "TUBE_WALL_T_M": overrides.get("TUBE_WALL_T_M", 0.0002),
        "WRITE_PNG": overrides.get("WRITE_PNG", 1),
        "X_RIGHT_M": overrides.get("X_RIGHT_M", 0.22),
        "X_RIGHT_PHYS_M": overrides.get("X_RIGHT_PHYS_M", 0.22),
        "YBOX_M": overrides.get("YBOX_M", 0.09),
        },
    )


# ── Backward-compatible single-run case ────────────────────────────
CASE = make_case()


# ── Sweep specification ──────────────────────────────────────────
from sweep_types import SweepAxis, SweepSpec, linspace, arange  # noqa: E402

SWEEP = SweepSpec(
    axes=[
    SweepAxis(name="PLASMA_NI_M3", values=[1e+18, 2e+18, 3e+18, 4e+18, 5e+18]),
    SweepAxis(name="AP_RAD", values=[0.001, 0.0015, 0.002, 0.0025, 0.003]),
    ],
    mode="product",
    reduce=False,
    tag="RadNi_Sweep",
)
