"""
Curved grid case file — generated by beamlet_layout_gui  [2026-05-06 15:58]

Load with:  python curved_grid_pipeline.py --config curved_grid_case_example.py
Dry-run:    python curved_grid_pipeline.py --config curved_grid_case_example.py --dry-run
Profile:    python curved_grid_pipeline.py --config curved_grid_case_example.py --plot profile.png
"""
import math
from curved_grid_pipeline import (
    Aperture, Chamfer, BeamletPair, GridCurvature,
    CurvedGridDefinition, CurvedSimulationCase,
    make_apertures_from_pairs,
)

# ── Electrode geometry ──────────────────────────────────────────
R_SCR_M         = 0.3   # screen radius of curvature (m)
R_ACC_M         = 0.292   # accel  radius of curvature (m)  [concentric]
SCREEN_T_M      = 0.006
ACCEL_T_M       = 0.006
GAP_AFTER_M     = 0.002
VS_V            = 0.0
VA_V            = -10000.0
AP_RADIUS_M     = 0.002

# ── Aperture offsets (m) ─────────────────────────────────────────
SCREEN_OFFSETS_M = [0]
# Arc-length on the accel sphere from the concentric (zero-steering) position.
# Zero = radial line from focal point passes through both aperture centres.
# Positive = accel aperture displaced outward; negative = inward.
STEERING_ARCS_M  = [0]

PAIRS = [
    BeamletPair(screen_offset_m=s, steering_arc_m=arc, screen_radius_m=AP_RADIUS_M)
    for s, arc in zip(SCREEN_OFFSETS_M, STEERING_ARCS_M)
]
screen_apertures, accel_apertures = make_apertures_from_pairs(
    PAIRS, mirror=False, R_scr_m=R_SCR_M, R_acc_m=R_ACC_M
)

# ── Simulation case ────────────────────────────────────────────
CASE = CurvedSimulationCase(
    grids=[
        CurvedGridDefinition(
            name="screen",
            voltage_v=VS_V,
            thickness_m=SCREEN_T_M,
            gap_after_m=GAP_AFTER_M,
            apertures=screen_apertures,
            curvature=GridCurvature(radius_m=R_SCR_M, concave_upstream=True),
            mirror=True,
        ),
        CurvedGridDefinition(
            name="accel",
            voltage_v=VA_V,
            thickness_m=ACCEL_T_M,
            gap_after_m=0.0,
            apertures=accel_apertures,
            curvature=GridCurvature(radius_m=R_ACC_M, concave_upstream=True),
            mirror=True,
        ),
    ],
    env={
        "ENABLE_IONS": 1,
        "H": 0.0001,
        "PLASMA_NI_M3": 1e+16,
        "PNG_NAME": "curved_grid_geom.png",
        "RESULTS_DIR": "results",
        "RUN_PREFIX": "curved_grid_PerBExpansionTest_1B_300mRad_2mmAPRad_4mmGap",
        "RUN_SOLVE": 1,
        "SC_FACTOR": 0.0005,
        "TUBE_WALL_T_M": 0.0002,
        "WRITE_PNG": 1,
        "X_RIGHT_M": 0.22,
        "X_RIGHT_PHYS_M": 0.22,
        "YBOX_M": 0.09,
    },
)
