"""
Curved grid case file — generated by beamlet_layout_gui  [2026-04-03 14:21]

Load with:  python curved_grid_pipeline.py --config curved_grid_case_exported1.py
Dry-run:    python curved_grid_pipeline.py --config curved_grid_case_exported1.py --dry-run
Profile:    python curved_grid_pipeline.py --config curved_grid_case_exported1.py --plot profile.png
"""
import math
from curved_grid_pipeline import (
    Aperture, Chamfer, BeamletPair, GridCurvature,
    CurvedGridDefinition, CurvedSimulationCase,
    make_apertures_from_pairs,
)

# ── Electrode geometry ──────────────────────────────────────────
R_SCR_M         = 0.1   # screen radius of curvature (m)
R_ACC_M         = 0.092175416   # accel  radius of curvature (m)  [concentric]
SCREEN_T_M      = 0.005
ACCEL_T_M       = 0.005
GAP_AFTER_M     = 0.006
VS_V            = 0.0
VA_V            = -15000.0
AP_RADIUS_M     = 0.0015

# ── Aperture offsets (m) ─────────────────────────────────────────
SCREEN_OFFSETS_M = [0, 0.015, 0.025]
ACCEL_OFFSETS_M  = [0, 0.013826312, 0.023043854]

PAIRS = [
    BeamletPair(screen_offset_m=s, accel_offset_m=a, screen_radius_m=AP_RADIUS_M)
    for s, a in zip(SCREEN_OFFSETS_M, ACCEL_OFFSETS_M)
]
screen_apertures, accel_apertures = make_apertures_from_pairs(PAIRS, mirror=False)

# ── Simulation case ────────────────────────────────────────────
CASE = CurvedSimulationCase(
    grids=[
        CurvedGridDefinition(
            name="screen",
            voltage_v=VS_V,
            thickness_m=SCREEN_T_M,
            gap_after_m=GAP_AFTER_M,
            apertures=screen_apertures,
            curvature=GridCurvature(radius_m=R_SCR_M, concave_upstream=True),
            mirror=True,
        ),
        CurvedGridDefinition(
            name="accel",
            voltage_v=VA_V,
            thickness_m=ACCEL_T_M,
            gap_after_m=0.0,
            apertures=accel_apertures,
            curvature=GridCurvature(radius_m=R_ACC_M, concave_upstream=True),
            mirror=True,
        ),
    ],
    env={
        "ENABLE_IONS": 1,
        "H": 0.0001,
        "PNG_NAME": "curved_grid_geom.png",
        "RESULTS_DIR": "results",
        "RUN_PREFIX": "curved_grid_test_fix",
        "RUN_SOLVE": 1,
        "SC_FACTOR": 0.0005,
        "TUBE_WALL_T_M": 0.0002,
        "WRITE_PNG": 1,
        "X_RIGHT_M": 0.025,
        "X_RIGHT_PHYS_M": 0.55,
        "YBOX_M": 0.090,
    },
)
