"""
Curved grid sweep case — generated by curved_grid_pipeline  [2026-05-07 13:12]

Single run:  python curved_grid_pipeline.py --config curved_grid_case_example_sweep_B.py
Dry-run:     python curved_grid_pipeline.py --config curved_grid_case_example_sweep_B.py --dry-run
Sweep:       python curved_grid_pipeline.py --config curved_grid_case_example_sweep_B.py --sweep
Array task:  python curved_grid_pipeline.py --config curved_grid_case_example_sweep_B.py \
                 --sweep-task $SLURM_ARRAY_TASK_ID
"""
import math
from curved_grid_pipeline import (
    Aperture, Chamfer, BeamletPair, GridCurvature,
    CurvedGridDefinition, CurvedSimulationCase,
    make_apertures_from_pairs,
    concentric_accel_radius, concentric_accel_offsets,
)

# ── Electrode geometry ──────────────────────────────────────────
R_SCR_M         = 0.3   # screen radius of curvature (m)
R_ACC_M         = 0.292   # accel  radius of curvature (m)  [concentric]
SCREEN_T_M      = 0.006
ACCEL_T_M       = 0.006
GAP_AFTER_M     = 0.002
VS_V            = 0.0
VA_V            = -10000.0
AP_RAD_M     = 0.002

# ── Aperture offsets (m) ─────────────────────────────────────────
SCREEN_OFFSETS_M = [0, 0.007, 0.014, 0.021, 0.028, 0.035, 0.042, 0.049, 0.056, 0.063, 0.07, 0.077, 0.084]
# Arc-length on the accel sphere from the concentric (zero-steering) position.
STEERING_ARCS_M  = [0, -1.0130785e-18, -2.026157e-18, 0, -4.052314e-18, 0, 0, -8.1046281e-18, -8.1046281e-18, 0, 0, 0, 0]


# ── Parameterised case factory ────────────────────────────────────
def make_case(**overrides):
    """Return a CurvedSimulationCase built from module constants.

    Each constant is replaced by the corresponding value in *overrides*
    when supplied, allowing the sweep runner to vary individual
    parameters without mutating module state.
    """
    r_scr_m      = overrides.get("R_SCR_M",     R_SCR_M)
    r_acc_m_base = overrides.get("R_ACC_M",     R_ACC_M)
    screen_t_m   = overrides.get("SCREEN_T_M",  SCREEN_T_M)
    accel_t_m    = overrides.get("ACCEL_T_M",   ACCEL_T_M)
    gap_after_m  = overrides.get("GAP_AFTER_M", GAP_AFTER_M)
    vs_v         = overrides.get("VS_V",         VS_V)
    va_v         = overrides.get("VA_V",         VA_V)
    ap_rad_m  = overrides.get("AP_RAD_M", AP_RAD_M)

    # Re-derive R_ACC_M when R_SCR_M or geometry changes
    if "R_ACC_M" not in overrides:
        r_acc_m = concentric_accel_radius(
            r_scr_m, screen_t_m, gap_after_m, SCREEN_OFFSETS_M
        )
    else:
        r_acc_m = r_acc_m_base

    pairs = [
        BeamletPair(
            screen_offset_m=s,
            steering_arc_m=arc,
            screen_radius_m=ap_rad_m,
        )
        for s, arc in zip(SCREEN_OFFSETS_M, STEERING_ARCS_M)
    ]
    screen_apertures, accel_apertures = make_apertures_from_pairs(
        pairs, mirror=False, R_scr_m=r_scr_m, R_acc_m=r_acc_m
    )

    return CurvedSimulationCase(
        grids=[
            CurvedGridDefinition(
                name="screen",
                voltage_v=vs_v,
                thickness_m=screen_t_m,
                gap_after_m=gap_after_m,
                apertures=screen_apertures,
                curvature=GridCurvature(radius_m=r_scr_m, concave_upstream=True),
                mirror=True,
            ),
            CurvedGridDefinition(
                name="accel",
                voltage_v=va_v,
                thickness_m=accel_t_m,
                gap_after_m=0.0,
                apertures=accel_apertures,
                curvature=GridCurvature(radius_m=r_acc_m, concave_upstream=True),
                mirror=True,
            ),
        ],
        env={
        "ENABLE_IONS": overrides.get("ENABLE_IONS", 1),
        "H": overrides.get("H", 0.0001),
        "PLASMA_NI_M3": overrides.get("PLASMA_NI_M3", 1e+16),
        "PNG_NAME": overrides.get("PNG_NAME", "curved_grid_geom.png"),
        "RESULTS_DIR": overrides.get("RESULTS_DIR", "results"),
        "RUN_PREFIX": overrides.get("RUN_PREFIX", "CurvedGrid_SweepTest_"),
        "RUN_SOLVE": overrides.get("RUN_SOLVE", 1),
        "SC_FACTOR": overrides.get("SC_FACTOR", 0.0005),
        "TUBE_WALL_T_M": overrides.get("TUBE_WALL_T_M", 0.0002),
        "WRITE_PNG": overrides.get("WRITE_PNG", 1),
        "X_RIGHT_M": overrides.get("X_RIGHT_M", 0.02),
        "X_RIGHT_PHYS_M": overrides.get("X_RIGHT_PHYS_M", 0.22),
        "YBOX_M": overrides.get("YBOX_M", 0.09),
        },
    )


# ── Backward-compatible single-run case ────────────────────────────
CASE = make_case()


# ── Sweep specification ──────────────────────────────────────────
from sweep_types import SweepAxis, SweepSpec, linspace, arange  # noqa: E402

SWEEP = SweepSpec(
    axes=[
    SweepAxis(name="AP_RAD", values=[0.001, 0.002, 0.003, 0.004]),
    ],
    mode="product",
    reduce=False,
    tag="APRad1_4mm",
)
